### ISSUE TITLE
Incorrect Calibration And Firmware Rocket4

### ISSUE THREAD

**Issue by stevegtaylor** [jlab-sensing/MFC#13]
@jmadden173 
Rocket4 has incorrect calibration and firmware.

**Comment by jmadden173** [comment]
I thought this issue was in reference to not being able to calibrate the rocketlogger with a generic SMU. I think I sent you the logs from when I tried running the calibration. Can we move this to the official Rocketlogger repo: https://github.com/ETHZ-TEC/RocketLogger

------- Original Message -------
